name: resume_critiquer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  file_picker: ^10.3.8
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  syncfusion_flutter_gauges: ^31.1.19
  flex_seed_scheme: ^3.5.1
  google_fonts: ^6.3.2
  mobx: ^2.6.0
  flutter_mobx: ^2.3.0
  get_it: ^9.2.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  open_file: ^3.5.10
  printing: ^5.14.2
  syncfusion_flutter_pdfviewer: ^31.1.19
  json_serializable: ^6.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  hive_generator: ^2.0.1
  mobx_codegen: ^2.7.1
  # flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto/static/Roboto-Regular.ttf
    - assets/fonts/Roboto/static/Roboto-Bold.ttf

